### ISSUE TITLE
Расписание-2020-Q3 / HTML для начинающих / Текст в HTML 11/41

### ISSUE THREAD

**Issue by Vitaly330** [hexlet-basics/exercises-html#62]
https://docs.google.com/spreadsheets/d/1oM2O8DtjC0HodB3j7hcIResaWBw8P18tXkOl1ymelvE/htmlview?pru=AAABdIhB2BQ*rRz4iKFZPWu6msdGEEzRoQ#gid=1641310155
https://ru.code-basics.com/languages/html/modules/hypertext/lessons/table

При проверке ломается.
Сообщение в консоли:
/usr/lib/node_modules/chai/lib/chai/assertion.js:141
      throw new AssertionError(msg, {
      ^
AssertionError: expected [ Array(3) ] to have a length of 2 but got 3
    at /exercises-html/modules/20-hypertext/50-table/test.js:9:23
    at test (/exercises-html/src/tests.js:14:5)
    at Object.<anonymous> (/exercises-html/modules/20-hypertext/50-table/test.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  showDiff: true,
  actual: 3,
  expected: 2
}

Решение:
<table>
    <thead>
        <tr>
            <th>Первая ячейка</th>
            <th>Вторая ячейка</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Первая ячейка</td>
            <td>Вторая ячейка</td>
        </tr>
        <tr>
            <td>Первая ячейка</td>
            <td>Вторая ячейка</td>
        </tr>
        <tr>
            <td>Первая ячейка</td>
            <td>Вторая ячейка</td>
        </tr>
    </tbody>
</table>

**Comment by Psixodelik** [comment]
Здравствуйте

Обратите внимание, что всего должно быть три строки, включая заголовки. У вас суммарно четыре строки
